config/routes.rb
Rails.application.routes.draw do
  resources :events

 root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
 validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def index
		@events = Event.all
	end

	def show
			@event = Event.find(params[:id])
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)

		if @event.save
			redirect_to @event
		else
			render 'new'
		end
	end

	def update
		@event  = Event.find(params[:id])

		if @event.update(article_params)
			redirect_to @event
		else
			render 'edit'
		end
	end

	def destroy
  @event = Event.find(params[:id])
  @event.destroy
 
  redirect_to events_path
end

		private
		def event_params
			params.require(:event).permit(:title, :text)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
 
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@event.errors.count, "error") %> prohibited
        this event from being saved:
      </h2>
      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
 <p>
    <%= f.label :location%><br>
    <%= f.text_area :location %>
  </p>

  <p>
    <%= f.label :description%><br>
    <%= f.text_area :description %>
  </p>

<p>
    <%= f.label :date%><br>
    <%= f.text_area :date %>
  </p>
 <p>
    <%= f.label :time%><br>
    <%= f.text_area :time %>
  </p>
 
  <p>
    <%= f.label :cost%><br>
    <%= f.text_area :cost %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>
 
<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>
 
<%= link_to 'New Event', new_event_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Location</th>
    <th>Description</th>
    <th>Date</th>
    <th>Time</th>
    <th>Cost</th>
     <th colspan="2"></th>
  </tr>
 
  <% @events.each do |event| %>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.location %></td>
      <td><%= event.description %></td>
      <td><%= event.date %></td>
      <td><%= event.time %></td>
      <td><%= event.cost %></td>
       <td><%= link_to 'Show', event_path(event) %></td>
      <td><%= link_to 'Edit', edit_event_path(event) %></td>
      <td><%= link_to 'Destroy', event_path(event),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>
 
<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @event.cost %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>



<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Techeverything</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello rails!</h1>
<%= link_to 'My Events', controller: 'events' %>